services:
  sbom-creator:
    build: .
    ports:
      - "127.0.0.1:18082:8080"
    env_file: .env
    volumes:
      - ./workspace:/workspace
      - ./secrets:/run/secrets:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"
    cpus: 2
    mem_limit: 2g

